name: 'PR Tone Lint'
description: 'A tone linter for code reviews. Catches blame language, scores it, and suggests neutral rewrites — automatically.'
author: 'your-github-username'

branding:
  icon: 'message-square'
  color: 'yellow'

inputs:
  github-token:
    description: 'GitHub token for posting comments'
    required: true
  openai-api-key:
    description: 'OpenAI API key for tone analysis'
    required: true
  blame-threshold:
    description: 'Score threshold (0-100) above which a comment is flagged'
    required: false
    default: '60'
  tone:
    description: 'Bot personality: strict, balanced, or humorous'
    required: false
    default: 'balanced'
  post-on-borderline:
    description: 'Whether to post on borderline comments (score 31-59)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Build
      run: npm run build
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run
      run: node dist/index.js
      shell: bash
      working-directory: ${{ github.action_path }}
